In [ ]:
#Introduction of pandas
# pandas is opensource library and used to handle data manipulation
#data sturucture of pandas::::
# (1). series---->this is one dimensional
# (2). DataFrame----> this is multi-dimensional array

In [ ]:

import pandas as pd

In [ ]:
a=pd.Series([1,45,112,45,15])
a

0      1
1     45
2    112
3     45
4     15
dtype: int64

In [ ]:
#(2)data frame:
b={
    "emp_id": ["1a","2b","3c","4d"],
    "emp_name": ['sam','rahul','ankit','gaurav'],
    "department": ['it','sales','hr','it'],
    "salary": [21000,24000,25540,65000]

}

In [ ]:
df=pd.DataFrame(b)
print(df)

  emp_id emp_name department  salary
0     1a      sam         it   21000
1     2b    rahul      sales   24000
2     3c    ankit         hr   25540
3     4d   gaurav         it   65000

In [ ]:
#2nd day

In [ ]:
##export our dataframe

In [ ]:
df=pd.read_csv("/content/covid_toy - covid_toy.csv")
# To check if the file exists or to see the correct file name, you can run:
# !ls /content/

FileNotFoundError: [Errno 2] No such file or directory: '/content/covid_toy - covid_toy.csv'

In [ ]:
df.head(2)

  emp_id emp_name department  salary
0     1a      sam         it   21000
1     2b    rahul      sales   24000

In [ ]:
df.isnull().sum()

emp_id        0
emp_name      0
department    0
salary        0
dtype: int64

In [ ]:
#descrite (catagorical) --> we can't divide furthur EX.-result(pass/fail)
# marital status,number of employees
#catgorical (continues) ---> we can divide futhur ex.-distance(km),birth,salary

In [ ]:
# if data is descrite --> most frequent
# if data is continues ---> mean

In [ ]:
df['fever']=df['fever'].fillna(df['fever'].mean())

KeyError: 'fever'

In [ ]:
df['has_covid'].value_counts()

NameError: name 'df' is not defined

In [ ]:
df['city'].value_counts()

In [ ]:
df['gender']=df['gender'].map({"Female":0,"Male":1})

In [ ]:
df['cough']=df['cough'].map({"Mild":0,"Strong":1})

In [ ]:
df['city']=df['city'].map({"Kolkata":0,"Bangalore":1,"Delhi":2,"Mumbai":3})

In [ ]:
df['has_covid']=df['has_covid'].map({"No":0,"Yes":1})

In [ ]:
df.sample(5)

In [ ]:
df.dtypes

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df_new=pd.read_csv("/content/covid_toy - covid_toy.csv")

In [ ]:
df_new=df_new.dropna()

In [ ]:
df.head(3)

In [ ]:
a=df[['gender','fever']][3:7]=50

In [ ]:
df['fever'][1]=500

In [ ]:
df.head(2)

In [ ]:
df=df.rename(columns={"fever":"updated_fever"})

In [ ]:
df.head()

In [ ]:
#EDA ==> EXPLORATORT DATA ANALYSIS

In [ ]:
# PARTS OF EDA
1 .UNIVARIAENT ANALYSIS
2 BIVERIAENT ANALYSIS
3.MULTIVARIAENT ANYASIS

In [ ]:
DATA TYPES:
1.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
!pip install matplotlib
!pip install seaborn

Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [ ]:
df=pd.read_csv('/content/titanic.csv')

NameError: name 'pd' is not defined

In [ ]:
df.sample(5)

In [ ]:
df['Survived'].value_counts()

In [ ]:
df['Survived'].value_counts().plot(kind='bar')

In [ ]:
df['Survived'].value_counts()

In [ ]:
import seaborn as sns
import matplotlib as plt

In [ ]:
tips=sns.load_dataset('tips')

In [ ]:
sns.scatterplot(x=tips['total_bill'],
                y=tips['tip'])  #df['total_bill']

In [ ]:
sns.scatterplot(x="total_bill",
                y="tip",data=tips,
                hue=tips['sex'],style=tips['smoker'])  #df['total_bill']

In [ ]:
#heatmap(categorical-categorical)
p=pd.crosstab(tips['day'],tips['time'])
p

In [ ]:
sns.heatmap(p)

In [ ]:
# employee attrition anaysis is a type of behavioural analysis where we study the
#behavioural and characterstics of employees who left the organization and compare their characterstics
#with the current emplooyees to find the employees who may leave the organization soon.

In [ ]:
df=pd.read_csv('/content/Attrition - Attrition.csv')

In [ ]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [ ]:
!pip install plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (25.0)

In [ ]:
import plotly.graph_objects as go
import plotly.io as pio
pio.templates.default="plotly_white"

In [ ]:
print(df.isnull().sum())

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [ ]:
#check persentages of attrition by department

In [ ]:
# filter the data to show only "YES" values in the "ATTRITION" coloumn

In [ ]:
attr_df=df[df['Attrition']=='Yes']

In [ ]:
attr_df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
14,28,Yes,Travel_Rarely,103,Research & Development,24,3,Life Sciences,1,19,...,2,80,0,6,4,3,4,2,0,3
21,36,Yes,Travel_Rarely,1218,Sales,9,4,Life Sciences,1,27,...,2,80,0,10,4,3,5,3,0,3
24,34,Yes,Travel_Rarely,699,Research & Development,6,1,Medical,1,31,...,3,80,0,8,2,3,4,2,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1438,23,Yes,Travel_Frequently,638,Sales,9,3,Marketing,1,2023,...,1,80,1,1,3,2,1,0,1,0
1442,29,Yes,Travel_Rarely,1092,Research & Development,1,4,Medical,1,2027,...,2,80,3,4,3,4,2,2,2,2
1444,56,Yes,Travel_Rarely,310,Research & Development,7,2,Technical Degree,1,2032,...,4,80,1,14,4,1,10,9,9,8
1452,50,Yes,Travel_Frequently,878,Sales,1,4,Life Sciences,1,2044,...,4,80,2,12,3,3,6,3,0,1
1461,50,Yes,Travel_Rarely,410,Sales,28,3,Marketing,1,2055,...,2,80,1,20,3,3,3,2,2,0

In [ ]:
attrition_by_dpt=attr_df.groupby(['Department']).size().reset_index(name="count")
attrition_by_dpt

               Department  count
0         Human Resources     12
1  Research & Development    133
2                   Sales     92

In [ ]:
#create a donut chart
fig=go.Figure(data=[go.Pie(
    labels=attrition_by_dpt['Department'],
    values=attrition_by_dpt['count'],
    hole=0.4,
    marker=dict(colors=['red','green']),
    textposition='inside'
)])
#to update layout
fig.update_layout(title='ATTRITION BY DEPARTMENT')

#show the chart
fig.show()

In [ ]:
attr_df=df[df['Attrition']=='Yes']
attrition_by_edu=attr_df.groupby(['EducationField']).size().reset_index(name="count")
attrition_by_edu

     EducationField  count
0   Human Resources      7
1     Life Sciences     89
2         Marketing     35
3           Medical     63
4             Other     11
5  Technical Degree     32

In [ ]:
#create a donut chart
fig=go.Figure(data=[go.Pie(
    labels=attrition_by_edu['EducationField'],
    values=attrition_by_edu['count'],
    hole=0.4,
    marker=dict(colors=['red','green']),
    textposition='inside'
)])
#to update layout
fig.update_layout(title='ATTRITION BY EducationField')

#show the chart
fig.show()

In [ ]:
attrition_by=attr_df.groupby(['YearsAtCompany']).size().reset_index(name="count")
attrition_by

    YearsAtCompany  count
0                0     16
1                1     59
2                2     27
3                3     20
4                4     19
5                5     21
6                6      9
7                7     11
8                8      9
9                9      8
10              10     18
11              11      2
12              13      2
13              14      2
14              15      1
15              16      1
16              17      1
17              18      1
18              19      1
19              20      1
20              21      1
21              22      1
22              23      1
23              24      1
24              31      1
25              32      1
26              33      1
27              40      1

In [ ]:
attrition_by=attr_df.groupby(['YearsSinceLastPromotion']).size().reset_index(name="count")
attrition_by

    YearsSinceLastPromotion  count
0                         0    110
1                         1     49
2                         2     27
3                         3      9
4                         4      5
5                         5      2
6                         6      6
7                         7     16
8                         9      4
9                        10      1
10                       11      2
11                       13      2
12                       14      1
13                       15      3

In [ ]:
attrition_by=attr_df.groupby(['Gender']).size().reset_index(name="count")
attrition_by

   Gender  count
0  Female     87
1    Male    150

In [ ]:
#create a donut chart
fig=go.Figure(data=[go.Pie(
    labels=attrition_by['Gender'],
    values=attrition_by['count'],
    hole=0.4,
    marker=dict(colors=['red','green']),
    textposition='inside'
)])
#to update layout
fig.update_layout(title='ATTRITION BY GENDER')

#show the chart
fig.show()

In [ ]:
#now we have a look at the realtion on monthly income and age by attration
import plotly.express as px

In [ ]:
fig=px.scatter (df,x="Age",y="MonthlyIncome",color="Attrition",trendline="ols")
fig.update_layout(title="Age vs monthly income by attrition")
fig.show()