In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("/content/Attrition - Attrition.csv")

In [ ]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [ ]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [ ]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.shape

(1470, 35)

In [ ]:
df.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [ ]:
df['Attrition'].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [ ]:
df['Department'].value_counts()

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

In [ ]:
df.groupby('EducationField').size()

EducationField
Human Resources      27
Life Sciences       606
Marketing           159
Medical             464
Other                82
Technical Degree    132
dtype: int64

In [ ]:
df.groupby('Attrition')['DailyRate'].count()

Attrition
No     1233
Yes     237
Name: DailyRate, dtype: int64

In [ ]:
df.groupby('Attrition')['YearsSinceLastPromotion'].count()

Attrition
No     1233
Yes     237
Name: YearsSinceLastPromotion, dtype: int64

In [ ]:
df.groupby('BusinessTravel').size()

BusinessTravel
Non-Travel            150
Travel_Frequently     277
Travel_Rarely        1043
dtype: int64

In [ ]:
len(df[(df['Age'] > 20) & (df['Attrition'] == 'Yes')])

221

In [ ]:
len(df[(df['Age'] > 40) & (df['Department'] == 'Research & Development')])

308

In [ ]:
len(df[(df['Attrition'] == 'Yes') & (df['BusinessTravel'] == 'Travel_Rarely')])

156

In [ ]:
df[(df['Attrition'] =='Yes') & (df['Department'] == 'Research & Development')]

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
14,28,Yes,Travel_Rarely,103,Research & Development,24,3,Life Sciences,1,19,...,2,80,0,6,4,3,4,2,0,3
24,34,Yes,Travel_Rarely,699,Research & Development,6,1,Medical,1,31,...,3,80,0,8,2,3,4,2,1,3
26,32,Yes,Travel_Frequently,1125,Research & Development,16,1,Life Sciences,1,33,...,2,80,0,10,5,3,10,2,6,7
34,24,Yes,Travel_Rarely,813,Research & Development,1,3,Medical,1,45,...,1,80,1,6,2,2,2,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1354,56,Yes,Travel_Rarely,1162,Research & Development,24,2,Life Sciences,1,1907,...,4,80,0,5,3,3,4,2,1,0
1375,32,Yes,Travel_Frequently,238,Research & Development,5,2,Life Sciences,1,1939,...,1,80,0,8,2,3,4,1,0,3
1390,28,Yes,Travel_Rarely,1404,Research & Development,17,3,Technical Degree,1,1960,...,1,80,1,6,2,2,4,1,0,3
1442,29,Yes,Travel_Rarely,1092,Research & Development,1,4,Medical,1,2027,...,2,80,3,4,3,4,2,2,2,2
1444,56,Yes,Travel_Rarely,310,Research & Development,7,2,Technical Degree,1,2032,...,4,80,1,14,4,1,10,9,9,8

In [ ]:
df[(df['EducationField'] == 'Technical Degree') & (df['Attrition'] == 'No')]

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
64,36,No,Travel_Rarely,1223,Research & Development,8,3,Technical Degree,1,83,...,2,80,3,17,2,3,17,14,12,8
86,23,No,Travel_Rarely,541,Sales,2,1,Technical Degree,1,113,...,3,80,1,3,3,3,0,0,0,0
95,54,No,Travel_Rarely,1217,Research & Development,2,4,Technical Degree,1,126,...,1,80,1,16,5,1,4,3,0,3
117,36,No,Travel_Frequently,1467,Sales,11,2,Technical Degree,1,154,...,3,80,1,10,6,3,9,7,2,8
128,22,No,Travel_Rarely,594,Research & Development,2,1,Technical Degree,1,169,...,3,80,1,3,2,3,2,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1340,36,No,Travel_Rarely,1266,Sales,10,4,Technical Degree,1,1880,...,1,80,1,10,4,3,10,9,1,7
1367,27,No,Travel_Rarely,1354,Research & Development,2,4,Technical Degree,1,1931,...,3,80,1,6,3,2,5,3,1,2
1370,47,No,Non-Travel,1169,Research & Development,14,4,Technical Degree,1,1934,...,3,80,1,16,4,4,8,7,1,7
1409,40,No,Travel_Frequently,692,Research & Development,11,3,Technical Degree,1,1985,...,1,80,1,10,2,4,10,9,9,4
1449,32,No,Travel_Rarely,529,Research & Development,2,3,Technical Degree,1,2038,...,4,80,0,4,4,3,4,2,1,2

In [ ]:
df[(df['Attrition'] == 'Yes') | (df['BusinessTravel'] == 'Non-Travel')]

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
14,28,Yes,Travel_Rarely,103,Research & Development,24,3,Life Sciences,1,19,...,2,80,0,6,4,3,4,2,0,3
17,22,No,Non-Travel,1123,Research & Development,16,2,Medical,1,22,...,2,80,2,1,2,2,1,0,0,0
20,24,No,Non-Travel,673,Research & Development,11,2,Other,1,26,...,4,80,1,5,5,2,4,2,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1444,56,Yes,Travel_Rarely,310,Research & Development,7,2,Technical Degree,1,2032,...,4,80,1,14,4,1,10,9,9,8
1447,36,No,Non-Travel,301,Sales,15,4,Marketing,1,2036,...,1,80,1,15,4,2,15,12,11,11
1452,50,Yes,Travel_Frequently,878,Sales,1,4,Life Sciences,1,2044,...,4,80,2,12,3,3,6,3,0,1
1461,50,Yes,Travel_Rarely,410,Sales,28,3,Marketing,1,2055,...,2,80,1,20,3,3,3,2,2,0
1463,31,No,Non-Travel,325,Research & Development,5,3,Medical,1,2057,...,2,80,0,10,2,3,9,4,1,7

In [ ]:
df.sort_values('Age', ascending=False)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1209,60,No,Travel_Rarely,370,Research & Development,1,4,Medical,1,1697,...,3,80,1,19,2,4,1,0,0,0
411,60,No,Travel_Rarely,422,Research & Development,7,3,Life Sciences,1,549,...,4,80,0,33,5,1,29,8,11,10
427,60,No,Travel_Frequently,1499,Sales,28,3,Marketing,1,573,...,4,80,0,22,5,4,18,13,13,11
879,60,No,Travel_Rarely,696,Sales,7,4,Marketing,1,1233,...,2,80,1,12,3,3,11,7,1,9
536,60,No,Travel_Rarely,1179,Sales,16,4,Marketing,1,732,...,4,80,0,10,1,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,18,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,1,405,...,3,80,0,0,2,3,0,0,0,0
301,18,No,Travel_Rarely,812,Sales,10,3,Medical,1,411,...,1,80,0,0,2,3,0,0,0,0
727,18,No,Non-Travel,287,Research & Development,5,2,Life Sciences,1,1012,...,4,80,0,0,2,3,0,0,0,0
1153,18,Yes,Travel_Frequently,544,Sales,3,2,Medical,1,1624,...,3,80,0,0,2,4,0,0,0,0
457,18,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,1,614,...,4,80,0,0,3,3,0,0,0,0

In [ ]:
df1=pd.read_csv("/content/linkedin-reviews.csv")

In [ ]:
df1

                                                Review  Rating
0    Does absolutely nothing for a LinkedIn beginne...       1
1                              Force close(galaxy tab)       1
2    Slow and it tries to upload your contacts with...       1
3    Add ability to customize the profile and move ...       4
4    Good app, but it's a pain that it's not possib...       4
..                                                 ...     ...
697  Can't trust, Going to uninstall just for that ...       1
698  It really gets me linked in with my friends. H...       5
699  It lacks most of what makes the other social n...       4
700  Really disappointed in the new version. Seems ...       2
701  One of the best looking and well designed apps...       5

[702 rows x 2 columns]

In [ ]:
df1['Review']

0      Does absolutely nothing for a LinkedIn beginne...
1                                Force close(galaxy tab)
2      Slow and it tries to upload your contacts with...
3      Add ability to customize the profile and move ...
4      Good app, but it's a pain that it's not possib...
                             ...
697    Can't trust, Going to uninstall just for that ...
698    It really gets me linked in with my friends. H...
699    It lacks most of what makes the other social n...
700    Really disappointed in the new version. Seems ...
701    One of the best looking and well designed apps...
Name: Review, Length: 702, dtype: object

In [ ]:
def rating(x):
  if x <= 2:
    return 'Bad'
  elif x == 3:
    return 'Avg'
  else:
    return  'Good'


df1['Rating'] = df1['Rating'].map(rating)

In [ ]:
df1['Rating'].sample()

196    Avg
Name: Rating, dtype: object

In [ ]:
bad = df1[df1['Rating'] == 'Bad']

In [ ]:
bad

                                                Review Rating
0    Does absolutely nothing for a LinkedIn beginne...    Bad
1                              Force close(galaxy tab)    Bad
2    Slow and it tries to upload your contacts with...    Bad
5    This app is poor and bad. Linkedin app on my H...    Bad
11   Piece of s**t app. Really? You want people to ...    Bad
..                                                 ...    ...
685                    it's worse than the old one....    Bad
686  HATE the new update/layout!!! So hard to look ...    Bad
694  Yikes... Talk about losing focus on your targe...    Bad
697  Can't trust, Going to uninstall just for that ...    Bad
700  Really disappointed in the new version. Seems ...    Bad

[364 rows x 2 columns]

In [ ]:
avg = df1[df1['Rating'] == 'Avg']
good = df1[df1['Rating'] == 'Good']

In [ ]:
avg

                                                Review Rating
9    Clean design with limited features. How about ...    Avg
10   App works fine but has limited functionality. ...    Avg
12   Simple. Basic. But works perfectly for main fu...    Avg
18   Not a bad start, but needs more features like ...    Avg
26                                   Wont let you edit    Avg
..                                                 ...    ...
673    Am not able to add people I find using the app.    Avg
680  Application as such ok. But missing possibilit...    Avg
689  Thinks there are no discussions in some of my ...    Avg
691                              Need to UI attractive    Avg
696  Still quite slow and flaky on the Galaxy S, bu...    Avg

[121 rows x 2 columns]

In [ ]:
df=pd.read_csv("/content/covid_toy.csv")

In [ ]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df.tail()

    age  gender  fever   cough       city has_covid
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

In [ ]:
df.sample()

    age  gender  fever cough       city has_covid
47   18  Female  104.0  Mild  Bangalore        No

In [ ]:
df.columns

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')

In [ ]:
len(df[df['has_covid']=='Yes'])

45

In [ ]:
'''chack missing value
fill mising value
transfor catgorical to numerical with map
based on target columns you have to divid data and perform train test splict'''

'chack missing value\nfill mising value\ntransfor catgorical to numerical with map\nbased on target columns you have to divid data and perform train test splict'

In [ ]:
df.value_counts()

age  gender  fever  cough   city       has_covid
27   Male    100.0  Mild    Delhi      Yes          2
5    Female  100.0  Mild    Kolkata    No           1
     Male    102.0  Mild    Kolkata    Yes          1
6    Female  104.0  Mild    Kolkata    Yes          1
8    Female  101.0  Mild    Kolkata    No           1
                                                   ..
82   Female  102.0  Strong  Bangalore  No           1
                            Kolkata    No           1
83   Female  101.0  Mild    Kolkata    No           1
     Male    98.0   Mild    Delhi      Yes          1
             103.0  Mild    Kolkata    No           1
Name: count, Length: 89, dtype: int64

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
df['fever']=df['fever'].fillna(df['fever'].mean())

In [ ]:
df['gender']=df['gender'].map({'Female':0,'Male':1})

In [ ]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [ ]:
df['cough']=df['cough'].map({'Mild':0,'Strong':1})

In [ ]:
df['city']=df['city'].map({'Kolkata':0,'Bangalore':1,'Delhi':2,'Mumbai':3})

In [ ]:
df['has_covid']=df['has_covid'].map({'Yes':0,'No':1})

In [ ]:
df

    age  gender  fever  cough  city  has_covid
0    60       1  103.0      0     0          1
1    27       1  100.0      0     2          0
2    42       1  101.0      0     2          1
3    31       0   98.0      0     0          1
4    65       0  101.0      0     3          1
..  ...     ...    ...    ...   ...        ...
95   12       0  104.0      0     1          1
96   51       0  101.0      1     0          0
97   20       0  101.0      0     1          1
98    5       0   98.0      1     3          1
99   10       0   98.0      1     0          0

[100 rows x 6 columns]

In [ ]:
x=df.drop(columns=['has_covid'])

In [ ]:
from sklearn.model_selection import train_test_split

y = df['has_covid']

x_train, x_test, y_train, y_test = train_test_split(x,
y,
test_size=0.2,
random_state=42)

print(df.shape)
print(x.shape)
print(x_train.shape)
print(x_test.shape)
print(y.shape)
print(y_train.shape)
print(y_test.shape)

(100, 6)
(100, 5)
(80, 5)
(20, 5)
(100,)
(80,)
(20,)

In [ ]:
import seaborn as sns

In [ ]:
x=sns.load_dataset('tips')

In [ ]:
x

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
x['sex']=x['sex'].map({'Male':0,'Female':1})